[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[tox]
envlist =
    py{310,311,312}-dj{32,42}-wp{68}-dyf{11,12}
    py{310,311,312,313,314}-dj{52}-wp{68}-dyf{11,12}
    py{312,313,314}-dj{60}-wp{68}-dyf{11,12}

[testenv]
commands =
    python -m pytest {posargs}
deps =
    pytest
    pytest-cov
    coverage[toml]
    dj32: django~=3.2.0
    dj42: django~=4.2.0
    dj52: django~=5.2.0
    dj60: django~=6.0.0
    wp68: weasyprint~=68.0
    dyf11: pydyf~=0.11.0
    dyf12: pydyf~=0.12.0

[testenv:py314-dj52-wp68-dyf12]
# update USING_COVERAGE in GitHub action when changing Python with coverage
commands =
    python -m pytest --cov django_weasyprint --cov-context test
