name: PyPI

on:
  release:
    types:
    - published
    - edited

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

    - name: Build package
      run: uv build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
